title: Github User
author: Github User # Your name!
avatar: ../assets/avatar.png ## Your Avatar, use the patch as if it were in "_layouts"
name_color: Red ##The color of your name
baseurl: /
email: Your Email!

about: I love to code using <code>JavaScript</code>, <code>HTML</code> and <code>Python</code> ## Details
description: >
  Your amazing description!

projects:
  - { name: "Project", repo: "Project Repo", image: "Project Image", website: "Website", package: "Package", details: "Description (You can use HTML elements)" }

social_links:
  github: GitHub User

permalink: /:title/
