title: DarkFolio
author: DarkFolio # Your name!
baseurl: /DarkFolio
avatar: ../assets/avatar.svg ## Your Avatar, use the patch as if it were in "_layouts"
name_color: Yellow ##The color of your name

about: I am a Jekyll Theme by RedYetiDev. I contain a blog page, a index page, and a project page.
description: >
  Your amazing description!

projects:
  - { name: "DarkFolio", repo: "https://github.com/RedYetiDev/DarkFolio", image: "../assets/DarkFolio.svg", website: "https://redyetidev.github.io/DarkFolio", details: I am a Jekyll Theme by RedYetiDev. I contain a blog page, a index page, and a project page." }

social_links:
  github: RedYetiDev/DarkFolio

permalink: /:title/
sass:
    sass_dir: _sass
